### ISSUE TITLE
Bootstrap-FileStyle causes jQuery-Validation to always return True

### ISSUE THREAD

**Issue by JungleGenius** [markusslima/bootstrap-filestyle#104]
Hi,

First of all thanks for a fantastic bit of code. I love using FileStyle on my forms.

However, I'm running into a bit of an issue. I'm using the Laravel 5 Javascript Validation package here:
"proengsoft/laravel-jsvalidation" that is basically a wrapper around "jzaefferer/jquery-validation". 

If a FileStyle input is located inside a form that I am validating using the jQuery Validation Plugin the validation always returns true regardless of any form errors.  I'm not sure if I should be asking you or the jQuery Validation Plugin folks so I am posting here first.

The strange thing I see in my Firefox logs is a reference var google being undefined whenever a FileStyle input is located inside a form.  I'm trying to track this all down but I thought I would open a ticket and see if you have any insights.

Thanks!

**Comment by markusslima** [comment]
You probably have to change the operation of your validation so that she can work with Filestyle. The original field is hidden for a new look can be put in its place.

**Comment by JungleGenius** [comment]
Hi, My apologies for not following up with a reply much sooner. As it turns out this was due to a conflict with the Google Maps JavaScript library. As long as you don't use both in/on the same page the Bootstrap Files Style works as it should. Not sure why or how, but I did not need a upload dialog on the same page as my Google Map so I never went far enough to find out why.

**Comment by markusslima** [comment]
If you can send an example in jsFiddle would be easier I understand
