### ISSUE TITLE
Click on input to open file

### ISSUE THREAD

**Issue by WouterDeRyck** [markusslima/bootstrap-filestyle#108]
I wish a click on the input field itself would open the file dialog as this is standard behaviour for the regular version.

**Comment by markusslima** [comment]
Be clearer

**Comment by WouterDeRyck** [comment]
When you click on the input field (where your filename appears), it would generally have the same behaviour as when you click on the button itself. So it would open the file dialog.
Should not matter if you click on A or B.

![image](https://cloud.githubusercontent.com/assets/15377764/12841760/6f757d1a-cbee-11e5-89c2-f535e82f4127.png)

**Comment by markusslima** [comment]
I understand your point of view. But the plugin has a text input field to display the file name. Logo HTML when the element is disabled it does not run events. If I remove the disabled attribute field will be editable and occur several problems. Then the plugin will work only on the button.
