### ISSUE TITLE
append files

### ISSUE THREAD

**Issue by fcpauldiaz** [markusslima/bootstrap-filestyle#112]
Is it possible to append files each time the field input is used?

**Comment by markusslima** [comment]
I do not understand your question

**Comment by fcpauldiaz** [comment]
Every time the input file is used it resets the files selected. Is there some way to accumulate the files in the input without losing the files previously selected?

**Comment by belkhalil** [comment]
yeah you can use a jquery plugin  to do it lik this
http://www.jqueryscript.net/form/Beautiful-jQuery-File-Upload-Plugin.html

2016-05-03 15:09 GMT+00:00 Pablo Díaz Márquez <notifications@github.com>:

> Every time the input file is used it resets the files selected. Is there
> some way to accumulate the files in the input without losing the files
> previously selected?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/markusslima/bootstrap-filestyle/issues/112#issuecomment-216559051>
>



-- 
Abdeljabar AIT BELKHALIL
Master Science de l'information et ingénierie
Faculté des Sciences Ben M'Sik
Université Hassan II - Casablanca, Maroc
+212 622 080 650

**Comment by belkhalil** [comment]
aitbelkhalil@hotmail.fr sent you an invitation to join MEGA.

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and
communication. Get 50 GB free!
---

Please create your free MEGA account by clicking on the following
link:
https://mega.nz/#newsignupcmVwbHkrMDBhZTcyZjA2YmI1ZTM5ODQ3ODk1ZDU2OTIwYmVjMDY5ZWFmYTRhNThmZjdlM2E2OTJjZjAwMDAwMDAxMTM0MDgxMjU5MmExNjljZTA4OWZjNWI3QHJlcGx5LmdpdGh1Yi5jb21GVitEkHSBoQ

Best regards,

Team MEGA

**Comment by markusslima** [comment]
This is a standard behavior of browsers. This is not the focus of the plugin, the plugin is intended to only customize the file input field.
