### ISSUE TITLE
Support for both button before and after

### ISSUE THREAD

**Issue by holtkamp** [markusslima/bootstrap-filestyle#114]
Currently one button is supported, either:

- before the input field
- after the input field

It might be nice to support both a button before and after. This way we can use icons to 'guide' the user into explaining what the input field is about. For example for image uploading:

![screen shot 2016-04-14 at 14 05 55](https://cloud.githubusercontent.com/assets/776405/14527468/897db9ba-024a-11e6-8224-92f8f30b6ba0.png)

[JSFiddle for the source](https://jsfiddle.net/v7dewcsa/1/)

**Comment by markusslima** [comment]
I understand your place but this type of design is not advisable. Both buttons should work which is not their proposal. As some of the buttons would be just to inform generate a cruel question to the user. Which button do I click?

**Comment by holtkamp** [comment]
thanks for the informative response. Note the one on the left is not really a button / can not be clicked. 

Bootstrap refers to this as an add-on Button: http://getbootstrap.com/components/#input-groups-basic

It DOES hint the user on what kind of action is expected from him...

**Comment by markusslima** [comment]
I understand your place. Currently I work with interface construction and interface optimization and usability. I can tell you exactly that kind of legend, in this particular case, only hinders the user's reading.

**Comment by holtkamp** [comment]
mmm, OK, what would be your suggested best practice? Maybe use an in-field
legend like "Please select an image..."?

I guess this issue can be closed for the time being...

**Comment by markusslima** [comment]
If you want to specify who should choose an image why not write "Choose an image" along with the file icon? While not as elegant, it is a simple, direct and objective message that explains exactly what should be done. https://jsfiddle.net/v7dewcsa/3/
