### ISSUE TITLE
Set value programmatically

### ISSUE THREAD

**Issue by rsercano** [markusslima/bootstrap-filestyle#115]
Hello,

first of all thanks for your work. I have a simple question, in one of my forms I'm using your filestyle plugin and trying to set it's input field value when the user clicks edit button. I mean here's the flow:

1. User enters some fields including one or more file inputs then saves them.
2. User wants to see what he/she chose and clicks edit button.
3. Now I want to set file input field's value with the existing choice of user (which I've saved already)

How to set file input value programmatically ?

**Comment by markusslima** [comment]
The file input field is only used for selecting files, this means that the field does not receive values unless your own operation.
If you have questions still send the link to an example in jsfiddle.net

**Comment by rsercano** [comment]
I've resolved this by changing dialog without input option. And put an input myself. (Setting file name value by myself to input = text field)

Thanks
