### ISSUE TITLE
Options via data attributes are not working

### ISSUE THREAD

**Issue by stefanfrede** [markusslima/bootstrap-filestyle#118]
Hi,

just wanted to let you know that your plugin is not working via the data attributes option, at least not for `data-iconName`, `data-buttonName`, and `data-buttonText`.

Via JavaScript it works just fine.

Best,
- Stefan

**Comment by markusslima** [comment]
Send an example in https://jsfiddle.net.

**Comment by stefanfrede** [comment]
I hope jsbin is ok too:
http://jsbin.com/vikuqi/edit?html,js,output

**Comment by markusslima** [comment]
Sorry for the delay. He missed in his element class="filestyle"
