### ISSUE TITLE
Glyphicons not working with current releases of Bootstrap?

### ISSUE THREAD

**Issue by SpiresAwake** [markusslima/bootstrap-filestyle#121]
I just spent an hour trying to get bootstrap-filestyle to work in my project. However, I couldn't really get the icon to work.
It just does not get displayed. I found out, that if you you remove the "icon-span-filestyle"-class from the <span>-element, it is actually working.
Not sure if this is a bug or if I'm doing anything wrong?

**Comment by markusslima** [comment]
Share an example of how you are using

**Comment by SpiresAwake** [comment]
Sure thing. This is my button:
```
    <div class="row">
        <div class="form-group">
            <input type="file" id="swFile" name="swFile" required>
        </div>
    </div>
```

And this is where I initialize it:
 
```
$(document).ready(function () {
        $('#swFile').filestyle({
            buttonBefore : true,
            iconName: 'glyphicon glyphicon-upload',
            buttonText: 'Datei auswählen…'
        });
[...]
```

**Comment by markusslima** [comment]
missing class filestyle

**Comment by SpiresAwake** [comment]
When I do this, the jQuery I posted gets overridden and everything looks like default, except for the icon. The icon still doesn't get shown until I remove the part I stated in my initial post.

**Comment by markusslima** [comment]
To verify that this is a bug or writing error you should send a link to your problem or reproduce the problem in jsFiddle. So I can analyze better.

**Comment by markusslima** [comment]
You may be missing something ne your code, such as the lack of any component or is there something else interfering. Unfortunately without seeing the error happening is almost impossible to solve it.

If you can send to the web a page reproducing this error I could easily identify the solution.

**Comment by SpiresAwake** [comment]
So, I just created an example site for you to check this out:
http://nbvtest.pansite.de/_test/

**Comment by markusslima** [comment]
No icon works on this page. I found in the files loaded the source file icons bootstrapping.
The sources of icons bootstrap are not being charged. Check your directories and see if the Fonts folder is in the correct location.

Open the console on this page and check the loading errors and see which files are missing.

**Comment by SpiresAwake** [comment]
Oh, I'm sorry, that was actually the bootstrap-filestyle.js where I did my changes to make it work. I'm using the original file downloaded from Github now and it immediately stopped working.

**Comment by markusslima** [comment]
main.css, line 22

font-family: "si-font" !important; 

There are sources being applied to the icons. Review your css as it is interfering with the thumbs.

**Comment by SpiresAwake** [comment]
I got the problem now, thanks for your help!
I was just thinking the problem was with the Filestye-class, since the Glyphicons worked everywhere else on the site.
