### ISSUE TITLE
css class "filestyle" not found

### ISSUE THREAD

**Issue by WeanaSchnitzl** [markusslima/bootstrap-filestyle#124]
Hi,

in your samples you use a css-class "filestyle". so, when i try this it doesn't work.
am i missing a css file? did not find one in your zip. even in bootstrap (3.3.6) it can't be found.

or am i thinking in a wrong way, and the css-class is nowhere defined becaus it's not needed...

thanx for info!

Best regard from Austria
Werner

**Comment by markusslima** [comment]
Problem is, I do not even know what's going on. Be clearer when defining a problem. Explaining in detail what happens.

Example in jsfiddle, please.

**Comment by WeanaSchnitzl** [comment]
Hi Markus,

the problem is very simple. You use in all your samples a css class
filestyle! but in your githib project is no css file included. so where do
get the class from?

thx for the info.

Regards
Werner

**Comment by markusslima** [comment]
There is no css included in the filestyle class, it only serves as a mandatory selector for the script.
Your problem should probably be file upload, but as there is no example I can not solve your problem more efficiently.
