### ISSUE TITLE
blueimp Jquery Fileupload onchange event

### ISSUE THREAD

**Issue by patrickaglibut** [markusslima/bootstrap-filestyle#126]
I'm stuck with this problem wherein filestyle does not change the input file value in the textbox and retains the first file selected. It seems the bug is when jquery.ui.widget.js is included but i'm not able to remove it as it's a requirement of the fileupload. This error persist in all types of browser (IE, Chrome, Firefox).

I've read about the onchange event bug for firefox but it did not help me solve the problem so I posted a new thread for this.

sample: https://rawgit.com/patrickaglibut/jquery-filestyle-fileupload/master/index.html

**Comment by markusslima** [comment]
The filestyle dont working with blueimp

**Comment by markusslima** [comment]
Internal questions

**Comment by patrickaglibut** [comment]
I see.. thanks for noting thank @markusslima
