### ISSUE TITLE
I'm newbe, how to install the package in the visual studio?

### ISSUE THREAD

**Issue by ballonura** [markusslima/bootstrap-filestyle#128]
Hey, sorry on the newbe question,
I wodnload the package from: http://markusslima.github.io/bootstrap-filestyle/
and want add it to my asp.net mvc project, thx.

**Comment by markusslima** [comment]
Did not understand your question, you should be more specific in your problem.

**Comment by ballonura** [comment]
I just need add this:
<script src="~/Scripts/bootstrap-filestyle.js"></script>
I do it, but after, it look like divided to 2 elements:
https://s28.postimg.org/n07dnjix9/Untitled.png

**Comment by markusslima** [comment]
You have a code structural problem. Unfortunately without me seeing an example of your code I can not help

**Comment by markusslima** [comment]
Read alert in https://github.com/markusslima/bootstrap-filestyle

**Comment by ballonura** [comment]
**The JS:**

`$(":file").filestyle({ buttonName: "btn-primary" });`


**The View:**

`<form action="uploadFile1()">
                        <input type="file" class="filestyle" accept=".png" data-buttonName="btn-primary">
                        <br>
                        <input type="submit" value="Upload">
                    </form>`

**Comment by markusslima** [comment]
You should develop a css problem and not javascript. In this case, you should analyze your html structure along with the css and verify the element is influencing the plugin.

**Comment by ballonura** [comment]
Ok, thx.
