### ISSUE TITLE
How can i use ng-model to get the form data?

### ISSUE THREAD

**Issue by taobataoma** [markusslima/bootstrap-filestyle#131]
`            
           <form class="signin form-horizontal">

                <fieldset>

                    <div class="form-group">

                        <div class="col-md-9 col-sm-9 col-xs-12">

                            <input type="file" class="filestyle" data-buttonName="btn-primary" ng-bind="picFile"
                                   ngf-select="(vm.fileSelected = true)">

                        </div>

                        <div ng-show="vm.fileSelected" class="col-md-3 col-sm-3 col-xs-12">

                            <button class="btn btn-primary" ng-click="vm.upload(picFile)">Do Uploads </button>

                        </div>

                    </div>

                </fieldset>

            </form>`
I used ng-model here, but in the controller, vm.upload funciton can not get picFile data, what can i do?

**Comment by markusslima** [comment]
Não tenho grandes e boas experiências com o angular mas posso te afirmar a alteração da manipulação dos dados faz com que você não consiga pegar os dados. Tente alterar a ordem dos fatores.

**Comment by taobataoma** [comment]
> Não tenho grandes e boas experiências com o angular mas posso te afirmar a alteração da manipulação dos dados faz com que você não consiga pegar os dados do input. Tente alterar a ordem dos fatores.

oh,oh,oh, can u tell me by English,please, and what code can i to change?

**Comment by markusslima** [comment]
http://translator.google.com

pt-br to en

**Comment by taobataoma** [comment]
thx.
