### ISSUE TITLE
Add a 'clear' icon to text box

### ISSUE THREAD

**Issue by hitched97** [markusslima/bootstrap-filestyle#132]
Would be nice to have to option to put a small **x** to the right of the text box containing the filename.  Clicking the **x** would invoke the _.clear()_ method.  [Select2](http://select2.github.io/select2) has this capability, using the _allowClear_ setting.

**Comment by hitched97** [comment]
Here's a stab at it, without configurability.

[filestyle-patch.txt](https://github.com/markusslima/bootstrap-filestyle/files/920405/filestyle-patch.txt)

**Comment by hitched97** [comment]
Also, the **x** should probably be muted (and have a different cursor?) when there is no file selected.

**Comment by hitched97** [comment]
I see now there is a fork with a more thorough implementation of this: https://github.com/Cediddi/bootstrap-filestyle/

**Comment by markusslima** [comment]
Sorry I did not answer before. This type of input can be done manually without problems, it is not necessary to implement such functionality.

**Comment by hitched97** [comment]
True, but it's much cleaner to set a flag than to add `$('#certificate_file_input').next().find('input').after('<div id="certificate_file_input-close" class="input-group-addon" style="padding:6px 4px;cursor:pointer;"><i class="fa fa-times"></i></div>');` and a corresponding on-click function for every file element.
