### ISSUE TITLE
Original file selection is sometimes not hidden.

### ISSUE THREAD

**Issue by hitched97** [markusslima/bootstrap-filestyle#133]
I ran into an instance where the original input element was not completely hidden when the filestyle was applied.  I don't know what triggers it, as it works fine in other places in the UI.  Might be related to use of [Panopta bootstrap wizard](https://github.com/amoffat/bootstrap-application-wizard).  I found I could fix it by adding this CSS to the style of the original input element (circa line 254):

				'width' : '1px',
				'height' : '1px',
				'top' : '1px',
				'left' : '1px',

Select2 uses these (among others) to hide the original input element.

Browser was Google Chrome, OS is Windows 7, bootstrap 3.3.7 is in use.

**Comment by markusslima** [comment]
Your problem is here ('top' : '1px', 'left' : '1px')
