### ISSUE TITLE
Not working on first pageload

### ISSUE THREAD

**Issue by PhpSriptKiddie** [markusslima/bootstrap-filestyle#134]
For some reason, filestyle doesn't seem to work on my page before reloading it. When visiting the site first time - or through incognito mode, filestyle is not applied to the element with class="filestyle". When trying to apply it manually with jquery through browser console, i get an error saying filestile is not a function.

However, as soon as the page is reloaded, it starts working.

What could possibly cause this?

Thanks!

**Comment by markusslima** [comment]
Verifique se o arquivo do plugin está sendo carregado corretamente.

**Comment by PhpSriptKiddie** [comment]
It should be loaded correctly. The plugin file is loaded in header using wp_enqueue_script.

**Comment by markusslima** [comment]
Teria como enviar o html do seu código para eu poder analisar?
