### ISSUE TITLE
Version numbers not following semantic versioning?

### ISSUE THREAD

**Issue by holtkamp** [markusslima/bootstrap-filestyle#140]
First of all thumbs up for this library, very nice. 

I was just wondering why it stopped working for our application that uses Bootstrap 3. The application depends on bootstrap-filestyle version `^1.2`. I found out it was upgraded recently to `1.3` which targets Bootstrap 4. The current versioning does not seem to follow the concepts of [semantic versioning](http://www.semver.org) using pattern `x.y.z`:

- `1.0.z` supports Bootstrap 2
- `1.2.z` supports Bootstrap 3
- `1.3.z` supports Bootstrap 4

According to semantic versioning: since the difference between the various Bootstrap versions are breaking, the major version should be bumped. The "major" version is the "x" in `x.y.z`.

So I would expect support for Bootstrap 4 to land in `2.y.z` instead of `1.3.z`. Might this be an idea to adopt for this library as well?

**Comment by markusslima** [comment]
Several updates are released among the most critical updates. The latest version compatible with the bootstrap3 is fully functional never stopped working. The critical updates are for updating and monitoring the bootstrap. So I do not develop into a compatibility model.

**Comment by holtkamp** [comment]
thanks for the response! I know `1.2.x` is still fully functional and works with Bootstrap 3. My point / advise / request would be: please consider adopting the versioning scheme as suggested by [semantic versioning](http://www.semver.org). 

This way other users have more fun on using your work and might consider contributing 😄 . It is quite common in the open source software world now...

**Comment by StudioMaX** [comment]
+1. We have "^1.2" in out bower.json and because of these non-BC changes the bootstrap-filestyle feature was broken after update.

**Comment by markusslima** [comment]
What you have to understand is, when there is a bootstrap update, there is usually a change in the interface and this prevents the compatibility of previous versions. The bootstrap itself is like that, so I do not see any problems. As improvements and fixes before version 1.3.0, then I swear I see no problems. The bower.js will not be compatible you will have to do manually.

**Comment by holtkamp** [comment]
> What you have to understand is, when there is a bootstrap update, there is usually a change in the interface and this prevents the compatibility of previous versions.

Ok, and if this library is updated, than the guide lines of semantic versioning suggest that if you implement support for these new verions, you bump the major version of *this* library as well. 

I have the feeling we are mis-communicating 😊, maybe somebody else can explain my suggestion better? @StudioMaX ?

**Comment by markusslima** [comment]
I will not, but feel free to submit a pull-request with this kind of implementation. So everyone would be happy. Unfortunately I do not have time to give this kind of support to the project.

**Comment by holtkamp** [comment]
>feel free to submit a pull-request with this kind of implementation

It does not even need a PR! You simply tag the version in GitHub 😄 

https://github.com/markusslima/bootstrap-filestyle/releases

- version `1.3.0 beta` should be deprecated / removed
- tag tag the version as `2.0.0 beta` and you are done!
