### ISSUE TITLE
Hi,clear method is not working when I submit form by ajax.

### ISSUE THREAD

**Issue by yinTang** [markusslima/bootstrap-filestyle#142]
The clear method of this plugin is not working. Because, when i use this method it didn't do clean operation but just create a new instance above the previous instance. It is my code ：
 $.ajaxFileUpload({
            type: "POST",
            url: "generateGreyLicense",
            dataType: "json",
            secureuri: false,
            fileElementId: ['licReqx'],
            data: params,
            success: function (data) {
               [$(":file").filestyle('clear');]([url](`url`))
            }
        });

**Comment by markusslima** [comment]
This plugin does not support bootstrap-filestyle so far due to the change of the input file element.
