### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by MGeurts** [markusslima/bootstrap-filestyle#145]
It would be nice if we could use the value="" parameter on this inputs. For instance...
```php
<input type="file" class="filestyle" id="NewPictureName" data-buttonName="btn-primary" value="<?php if ( isset($record[PictureName]) ) { echo $record[PictureName]; } ?>">
```
But at the moment the default value is not visible.

Thanks in advance.

**Comment by markusslima** [comment]
Can not, the file field has unique features in html. Of course this does not work with or without the plugin.
