### ISSUE TITLE
Not working inside an ng-repeat

### ISSUE THREAD

**Issue by declankelly170** [markusslima/bootstrap-filestyle#146]
I am repeating using filestyle, and I need to create Id's at runtime, using a value from the controller (id="training{{training.code}}").
The Id is sent to your code as id="training{{training.code}}", and not the controller value (e.g. "training1_star").
The button click therefore doesn't work.
I'm using Angular 1.3.8, and can't upgrade.
Any ideas?

**Comment by markusslima** [comment]
Example online?
