### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by aspyatkin** [markusslima/bootstrap-filestyle#147]
Hello,
The package version hosted on [npm](https://www.npmjs.com/package/bootstrap-filestyle) seems to be outdated. Could you please upload an update?

**Comment by FaridAghili** [comment]
You can use this package:
https://www.npmjs.com/package/@faridaghili/bootstrap-filestyle

This is the current (original - unmodified) version.

**Comment by aspyatkin** [comment]
Cool, thanks!
