### ISSUE TITLE
TypeError: element.filestyle is not a function

### ISSUE THREAD

**Issue by uvaisTrivecta** [markusslima/bootstrap-filestyle#153]
Hi , My self new to angular js, jus trying to upload a file and landed in the below '**TypeError: element.filestyle is not a function**'

jQuery v2.1.3
bootstrap-filestyle v1.1.2
angular v1.4.2

**Tag:**
`<input filestyle="" type="file" data-button-text="Single" data-class-button="btn btn-default" data-classinput="form-control inline" nv-file-select="" uploader="documentUploader" class="form-control" />`

**Error Log:**

TypeError: element.filestyle is not a function
    at link (http://localhost:8282/app/js/app.js:4678:19)
    at invokeLinkFn (http://localhost:8282/app/js/base.js:17858:9)
    at nodeLinkFn (http://localhost:8282/app/js/base.js:17358:11)
    at compositeLinkFn (http://localhost:8282/app/js/base.js:16749:13)
    at compositeLinkFn (http://localhost:8282/app/js/base.js:16753:13)
    at compositeLinkFn (http://localhost:8282/app/js/base.js:16753:13)
    at nodeLinkFn (http://localhost:8282/app/js/base.js:17353:24)
    at compositeLinkFn (http://localhost:8282/app/js/base.js:16749:13)
    at nodeLinkFn (http://localhost:8282/app/js/base.js:17353:24)
    at compositeLinkFn (http://localhost:8282/app/js/base.js:16749:13) <input filestyle="" type="file" data-button-text="Single" data-class-button="btn btn-default" data-classinput="form-control inline" nv-file-select="" uploader="documentUploader" class="form-control">

**Controller.js**
(function() {
    'use strict';

    angular
        .module('app.forms')
        .controller('FileUploadController', FileUploadController);

    FileUploadController.$inject = ['FileUploader'];
    function FileUploadController(FileUploader) {
        var vm = this;

        activate();

        ////////////////

        function activate() {
          var uploader = vm.uploader = new FileUploader({
              url: 'server/upload.php'
          });

          // FILTERS

          uploader.filters.push({
              name: 'customFilter',
              fn: function(/*item, options*/) {
                  return this.queue.length < 10;
              }
          });

          // CALLBACKS

          uploader.onWhenAddingFileFailed = function(item /*{File|FileLikeObject}*/, filter, options) {
              console.info('onWhenAddingFileFailed', item, filter, options);
          };
          uploader.onAfterAddingFile = function(fileItem) {
              console.info('onAfterAddingFile', fileItem);
          };
          uploader.onAfterAddingAll = function(addedFileItems) {
              console.info('onAfterAddingAll', addedFileItems);
          };
          uploader.onBeforeUploadItem = function(item) {
              console.info('onBeforeUploadItem', item);
          };
          uploader.onProgressItem = function(fileItem, progress) {
              console.info('onProgressItem', fileItem, progress);
          };
          uploader.onProgressAll = function(progress) {
              console.info('onProgressAll', progress);
          };
          uploader.onSuccessItem = function(fileItem, response, status, headers) {
              console.info('onSuccessItem', fileItem, response, status, headers);
          };
          uploader.onErrorItem = function(fileItem, response, status, headers) {
              console.info('onErrorItem', fileItem, response, status, headers);
          };
          uploader.onCancelItem = function(fileItem, response, status, headers) {
              console.info('onCancelItem', fileItem, response, status, headers);
          };
          uploader.onCompleteItem = function(fileItem, response, status, headers) {
              console.info('onCompleteItem', fileItem, response, status, headers);
          };
          uploader.onCompleteAll = function() {
              console.info('onCompleteAll');
          };

          console.info('uploader', uploader);
        }
    }
})();

Any help on the same is appreciated

**Comment by markusslima** [comment]
Probably your problem is loading. Filestyle is not ready when you need it.
if you have the page working online so you can look it would be easier to analyze your problem
