### ISSUE TITLE
clear() method adds a new instance instead of clearing existing file input

### ISSUE THREAD

**Issue by MindSculpt** [markusslima/bootstrap-filestyle#23]
On the error response of an AJAX call, my file input seems to stop updating the selected file. Using $(":file").filestyle('clear') only adds a new instance, rather than clearing the existing file input. Thoughts?

**Comment by davidbell** [comment]
I know this is an old thread but Google just brought me here so I thought I'd leave a note saying that this is working for me to post files via ajax, and then .filestyle('clear') is working to clear the input.

http://portfolio.planetjon.ca/2014/01/26/submit-file-input-via-ajax-jquery-easy-way/
