### ISSUE TITLE
Drag&Drop

### ISSUE THREAD

**Issue by simo2409** [markusslima/bootstrap-filestyle#49]
It would be nice to support drag&drop to populate input file (like the default input file)

**Comment by gpetrov** [comment]
Any news on this one? It will be really useful to have drag & drop available for all browsers

**Comment by cybibo** [comment]
can not set $(":file").filestyle({placeholder: "No file",disabled: true})?

**Comment by zenzei** [comment]
Hi. 

I manage to get this beahviour working (native selection with drag & drop in browsers, without ajax or async uploads) with some minor tweaks to the js, following this idea [.](http://www.quirksmode.org/dom/inputfile.html)

I'm not very good with git so I will paste the changes here. They are only minor style changes for the bootstrap-filestyle.js version 1.2.1. For simplicity replace lines 243 to 255 with these

```
			_self.$elementFilestyle = $('<div class="bootstrap-filestyle input-group"  style="position: absolute; top: 0px; left: 0px; z-index: 1;">' + html + '</div>');
			_self.$elementFilestyle.find('.group-span-filestyle').attr('tabindex', "0").keypress(function(e) {
			if (e.keyCode === 13 || e.charCode === 32) {
				_self.$elementFilestyle.find('label').click();
					return false;
				}
			});

			// hidding input file and add filestyle
			_self.$element.css({
				'-moz-opacity': 1,
				'filter': 'alpha(opacity: 1)',
				'opacity': 0,
				'position': 'relative',
				'text-align': 'right',
				'z-index': 2
			}).attr('tabindex', "-1").addClass('form-control').wrap('<div style="position: relative;"></div>').after(_self.$elementFilestyle);
```


In my app I also add these lines to avoid leaving the page if the user wrongly try to drag & drop to a "not" input file, as the browser will try to open the file leaving your current page. I know it's not the puporse of this library, but I put it here cause I think is related.

```
$(document).on("dragover drop", function(e) {
  if (!$(e.target).is("input[type='file']")) {
    e.preventDefault();  //don't navigate to file on drop (if the target isn't an input type file) 
  }
});
```
Is an almost global denied to all drag&drop events as my app doesn't need any of these except for the file inputs, you will need to adjust this in your app. Here another link that could help for that [.](http://stackoverflow.com/a/32044456) 

Hope it helps anybody
