### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by raph91** [markusslima/bootstrap-filestyle#79]
Hello
I wanted to add a border around the input, is this even possible?

This is not working (not even the btn-danger!!):
"input class="filestyle border" type="file" data-icon="false" data-classButton="btn btn-danger" data-buttonText="Browse..." "

.border {
    border:1px solid #990000;
}

Could you help me?

Regards

**Comment by markusslima** [comment]
better detail the visual effect you want to achieve. If you can send a picture would be even better

**Comment by markusslima** [comment]
It is possible but add that purpose. But you will have to apply this CSS in the plugin already run, add css to the input file will not work.

**Comment by raph91** [comment]
I want the same border around the box:
![unbenannt](https://cloud.githubusercontent.com/assets/10978129/6213662/6d8511e0-b5f2-11e4-8280-4199ec116746.png)

So I have to change the JS file? Where can I do that? There is no CSS "section"...
