### ISSUE TITLE
JavaScript minification errors when trying to use JsMinify

### ISSUE THREAD

**Issue by YovavGad** [markusslima/bootstrap-filestyle#80]
Looks like "not all code paths return a value"

/* Minification failed. Returning unminified contents.
(400,6304): run-time error JS1004: Expected ';'
(400,6304-6305): run-time error JS1195: Expected expression: :
(400,6346-6347): run-time error JS1002: Syntax error: }
(400,6362-6363): run-time error JS1002: Syntax error: }
(400,6363-6364): run-time error JS1195: Expected expression: )
(400,6364-6365): run-time error JS1002: Syntax error: }
(400,6365-6366): run-time error JS1195: Expected expression: )
(400,6366-6367): run-time error JS1002: Syntax error: }
(400,6367-6368): run-time error JS1195: Expected expression: )
 */

**Comment by markusslima** [comment]
From experience never compress a file already compressed it always generates errors.
Try using the uncompressed file in your project.
