### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by schel4ok** [markusslima/bootstrap-filestyle#82]
I put this code in my form

		<div class="form-group">
		<input type="file" class="filestyle" data-buttonName="btn-primary">
		</div>

It is automatically generate code like in your example, but it doesn't work.
You can see it here http://schel4ok.myjino.ru/public/contacts

I use bootstrap 3.3.2 + bootswatch paper
Your js is integrated at the end of uglified frontend.js.

**Comment by markusslima** [comment]
Não vejo aonde se encontra o problema. Por favor seja mais claro.
