### ISSUE TITLE
Add the package to npm

### ISSUE THREAD

**Issue by benediktschmitt** [markusslima/bootstrap-filestyle#85]
Is it already possible to install this package with npm?

If not, could you please add a package.json file?

Btw, thank you for this great plugin.

**Comment by ropez** [comment]
+1

**Comment by jaapz** [comment]
@markusslima i have create a PR for this issue, could you look at it?

**Comment by markusslima** [comment]
ty

**Comment by jbmikk** [comment]
@markusslima It would be appreciated if there was a release with a package.json file. Latest version 1.2.1 doesn't have it, and I would not like to add a master branch to my project, I would rather add a stable version. Maybe a 1.2.2 release could be made including the package.json file? Thank you.
