### ISSUE TITLE
after second use, it still displays the first file

### ISSUE THREAD

**Issue by sheffler** [markusslima/bootstrap-filestyle#87]
This may not be a standard use, but it is working pretty well for us, with the exception of one small detail.

I am using bootstrap-filestyle with jquery-fileupload.

Each time a user selects a file, it is immediately sent to cloud storage by using a POST.  It is convenient that the filename is sitting in the input area after the POST completes.  Now, if a user selects another file for uploading to cloud storage, it is sent correctly, but the input area still displays the first file.

I think that this is because the bootstrap-filestyle keeps a queue of filename (see pushNameFiles).

Here is the relevant code:

    <input id="fileupload" type="file" name="file" class="filestyle" />

and here is the Javascript that sends the files.

    $(function() {
       $('#fileupload').fileupload({

         add: function (e, data) {
           data.context=$("#filecontext").text("Uploading ...");
           $.ajax({
             type: "POST",
             url: "/cloudrecorder/presigned",
             cache: false,
             dataType: "JSON"
           }).success(function(d) {
             data.dataType = "XML";
             data.url = d["puturl"];
             data.formData = d["formdata"];
             data.submit();
           }).error(function(e) {
             console.log(["error", e]);
           });
         },

         done: function (e, data) {
           var location = $(data.jqXHR.responseXML).find("Location").text();
           var anchor = '<a href="' + location + '">' + location + '</a>';
           progressBar.css('width', "0%");
           data.context.text("Upload finished.");
         },

         fail: function(e, data) {
           console.log(["fail"]);
           progressBar.css('width', "100%").css('background', "red")
         },

         progressall: function(e, data) {
           console.log(['progress', data.loaded]);
           var progress = parseInt(data.loaded / data.total * 100, 10);
           progressBar.css('width', progress + '%');
         }
       });
     });

Do you have any idea on how to make the INPUT area show the MOST RECENT file added instead of the FIRST?

Thanks, T

**Comment by markusslima** [comment]
The plugin has problems with the use in conjunction with the fileupload. It presents a conflict between the handling element.

**Comment by markusslima** [comment]
#61
