### ISSUE TITLE
Allow using non-Bootstrap icon

### ISSUE THREAD

**Issue by aspyatkin** [markusslima/bootstrap-filestyle#88]
If you want to use e.g. Font-Awesome icons, you should add `fa` base class, and then `fa-someIconName`. However, this plugin assumes that you will always use `glyphicons` - the class name is hardcoded.

I think it would be great to allow specifying another base class for other icon sets via options.

**Comment by aspyatkin** [comment]
I thought that it might be even better to:
1. stop searching icon element by`.glyphicon` selector and, as the plugin makes the markup for button itself, make it e.g. `<span data-role="icon" ...>` and search by `data-role` attribute.
2. change the `iconName` option default value from `glyphicon-folder-open` to `glyphicon glyphicon-folder-open`.

**Comment by aspyatkin** [comment]
@markusslima Don't you mind if I make a pull request to implement this feature?

**Comment by markusslima** [comment]
Yes, of course you can. Once you are done I will analyze and include if no problems
