### ISSUE TITLE
Form feedback styling not handled

### ISSUE THREAD

**Issue by 127001** [markusslima/bootstrap-filestyle#93]
Form styling for .has-error and .has-feedback aren't handled. Makes errors look a bit strange.
![error](https://cloud.githubusercontent.com/assets/149222/8307226/c8f22c28-19bd-11e5-94e6-0ea745067be3.png)

**Comment by markusslima** [comment]
Send example in jsfiddle.net

**Comment by 127001** [comment]
http://jsfiddle.net/127001/ge5c6a4L/
The first field is a regular text input with an error, just vanilla bootstrap. The second field is extended with bootstrap-filestyle using class="filestyle"

**Comment by markusslima** [comment]
The filestyle need to use the label as a button and the bootstrap does not add the edge to the label. For this you can use this class and so pass on to other styles messages.

`.has-error label.btn {`
`   border: 1px solid #a94442;`
`}`

**Comment by 127001** [comment]
Okay, thanks for explaining.

**Comment by 127001** [comment]
I see this issue is still open, so I'll close it.
